name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  buildandpush:
    name: Build and Remote-Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.4.2'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
    - name: Check out code for the container build
      uses: actions/checkout@v2

    - name: Build Container
      run: |
        singularity build -F single_cell.sif Singularity
